# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

require 'yaml'

Vagrant.configure("2") do |config|
  config.vm.box = "cumulus-vx-2.5.3"

  properties = YAML.load_file("properties.yml")
  
  # Number of nodes to provision
  iter = 1

  # Spine definition and config
  1.upto(properties[:numSpines]) do |num|
    nodeName = ("s" + num.to_s).to_sym
    devName = ("s" + num.to_s)
    config.vm.define nodeName do |node|
      node.vm.host_name = devName
      1.upto(properties[:numLeaves]) do |leaf|
        leafname = ("l" + leaf.to_s)
        node.vm.network "private_network",
                        virtualbox__intnet: devName + "-" + leafname
      end
      
      node.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
          loopback_ip: properties[:ipAddrPrefix] + iter.to_s
        }
        ansible.playbook = "clospf.yml"
      end

      iter += 1
    end
  end

  # Leaf definition and config
  1.upto(properties[:numLeaves]) do |num|
    nodeName = ("l" + num.to_s).to_sym
    hostName = ("host" + num.to_s).to_sym
    devName = ("l" + num.to_s)
    nhostName = ("host" + num.to_s)
    config.vm.define nodeName do |node|
      node.vm.host_name = devName
      1.upto(properties[:numSpines]) do |spine|
        spinename = ("s" + spine.to_s)
        node.vm.network "private_network",
                        virtualbox__intnet: spinename + "-" + devName
      end
      #create interface to server
      servername = ("host" + devName)
      node.vm.network "private_network",
                        virtualbox__intnet: servername + "-" + devName

      node.vm.provision "ansible" do |ansible|
        ansible.extra_vars = {
          loopback_ip: properties[:ipAddrPrefix] + iter.to_s
        }
        ansible.playbook = "clospf.yml"
      end
      iter += 1
    end
    #Create the server
    config.vm.define hostName do |node|
      node.vm.host_name = nhostName
      node.vm.box = "ubuntu/trusty64"
      servername = ("host" + devName)
      node.vm.network "private_network", auto_config: false,
                        virtualbox__intnet: servername + "-" + devName
      node.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get upgrade
        #sudo apt-get install -y git build-essential autoconf texinfo libtool htop gawk
        #git clone git://git.savannah.nongnu.org/quagga.git
        dpkg -i /vagrant/quagga_0.99.24.1-2_amd64.deb
        sudo cp /vagrant/switchd /etc/init.d/
      SHELL
    end
  end
end
