
#-------------------------------------------------------------------------------
#
# Copyright 2015 Cumulus Networks, inc  all rights reserved
#
#-------------------------------------------------------------------------------

require 'rake'
require 'rspec/core/rake_task'
require 'yaml'

properties = YAML.load_file('properties.yml')

desc "Run serverspec on all hosts"
task :spec    => 'spec:all'
task :default => :spec

namespace :spec do

    allHosts = []
    1.upto(properties[:podsPerDC]) do |podNum|
        1.upto(properties[:racksPerPod]) do |rackNum|
            (1..2).each do |torSwNum|
                target = "p" + podNum.to_s + "r" + rackNum.to_s + "s" + torSwNum.to_s
                allHosts += [target]
                desc "Run serverspec tests to #{target}"
                RSpec::Core::RakeTask.new(target.to_sym) do |t|
                    ENV['TARGET_ROLE']    = "torSw"
                    ENV['TARGET_PAIR_ID'] = ((podNum-1)*(properties[:racksPerPod]+1) + rackNum).to_s
                    ENV['TARGET_SW_NUM']  = torSwNum.to_s
                    ENV['TARGET_HOST']    = target
                    t.pattern = "spec/switch/*_spec.rb"
                end
            end

            1.upto(properties[:hostsPerRack]) do |hostNum|
                target = "p" + podNum.to_s + "r" + rackNum.to_s + "h" + hostNum.to_s
                allHosts += [target]
                desc "Run serverspec tests to #{target}"
                RSpec::Core::RakeTask.new(target.to_sym) do |t|
                    ENV['TARGET_ROLE']    = "host"
                    ENV['TARGET_PAIR_ID'] = ((podNum-1)*(properties[:racksPerPod]*(properties[:hostsPerRack]+2)+2) + 
                                             (rackNum-1)*(properties[:hostsPerRack]+2) + hostNum).to_s
                    ENV['TARGET_SW_NUM']  = hostNum.to_s
                    ENV['TARGET_HOST']    = target
                    t.pattern = "spec/host/*_spec.rb"
                end
            end
        end

        (1..2).each do |podSwNum|
            target = "p" + podNum.to_s + "s" + podSwNum.to_s
            allHosts += [target]
            desc "Run serverspec tests to #{target}"
            RSpec::Core::RakeTask.new(target.to_sym) do |t|
                ENV['TARGET_ROLE']    = "podSw"
                ENV['TARGET_PAIR_ID'] = ((podNum-1)*(properties[:racksPerPod]+1) + 3).to_s
                ENV['TARGET_SW_NUM']  = podSwNum.to_s
                ENV['TARGET_HOST']    = target
                t.pattern = "spec/switch/*_spec.rb"
            end
        end
    end

    (1..2).each do |dcSwNum|
        target = "s" + dcSwNum.to_s
        allHosts += [target]
        desc "Run serverspec tests to #{target}"
        RSpec::Core::RakeTask.new(target.to_sym) do |t|
            ENV['TARGET_ROLE']    = "dcSw"
            ENV['TARGET_PAIR_ID'] = ((properties[:podsPerDC])*(properties[:racksPerPod]+1) + 1).to_s
            ENV['TARGET_SW_NUM']  = dcSwNum.to_s
            ENV['TARGET_HOST']    = target
            t.pattern = "spec/switch/*_spec.rb"
        end
    end

    task :all => allHosts

end
